export const members = [
  {
    id: '1-eipwei-ewiweo',
    name: 'Christian Nwamba',
    handle: '@christian',
    email: 'christian@chakra-ui.com',
    avatarUrl: 'https://bit.ly/code-beast',
    status: 'active',
    role: 'Senior Developer Advocate',
    rating: 4,
  },
  {
    id: '2-eipwei-ewiweo',
    name: 'Kent C. Dodds',
    handle: '@kent',
    email: 'kent@chakra-ui.com',
    status: 'active',
    role: 'Director of DX',
    rating: 4,
  },
  {
    id: '3-eipwei-ewiweo',
    name: 'Prosper Otemuyiwa',
    handle: '@prosper',
    email: 'prosper@chakra-ui.com',
    avatarUrl: 'https://bit.ly/prosper-baba',
    status: 'active',
    role: 'Director of Evangelism',
    rating: 4,
  },
  {
    id: '4-eipwei-ewiweo',
    name: 'Ryan Florence',
    handle: '@ryan',
    email: 'ryan@chakra-ui.com',
    avatarUrl: 'https://bit.ly/ryan-florence',
    status: 'active',
    role: 'Co-Founder',
    rating: 4,
  },
  {
    id: '5-eipwei-ewiweo',
    name: 'Segun Adebayo',
    handle: '@segun',
    email: 'segun@chakra-ui.com',
    avatarUrl: 'https://bit.ly/sage-adebayo',
    status: 'active',
    role: 'Frontend UI Engineer',
    rating: 4,
  },
]
